### ISSUE TITLE
Request: Healthcheck

### ISSUE THREAD

**Issue by modem7** [timlegge/docker-foswiki#18]
It might be a worthwhile idea to have the FosWiki container to have some form of healthcheck (curl, dig or similar) so that alerts/actions can occur if there's an issue with the database/web server.

**Comment by timlegge** [comment]
Hi

Yes, that can be added into the docker-compose I believe.  That being said,
the oly issue I have had with docker-foswiki over the last year was caused
by runaway health checks on a co-located docker container.

Tim

**Comment by mmallejac** [comment]
Hello,

Could you elaborate more on what kind of problem check you think about ?
Foswiki does not use database.
The docker-compose can be configured so that the containers are used within
the Foswiki service are restarted in case of failure (this is not done yet).

Monitoring is often an external program that validates for instance that
the foswiki server answers correctly within a certain time.
Icinga for instance is a marvelous tool for that purpose.

Michel

Le ven. 28 févr. 2020 à 19:41, Timothy Legge <notifications@github.com> a
écrit :

> Hi
>
> Yes, that can be added into the docker-compose I believe. That being said,
> the oly issue I have had with docker-foswiki over the last year was caused
> by runaway health checks on a co-located docker container.
>
> Tim
>

**Comment by timlegge** [comment]
Docker compose can add something like

healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

**Comment by modem7** [comment]
This is perfect thank you! 

I was trying curl but obviously it isn't installed with this particular container, so wget is absolutely fine for my particular needs at this time!

Appreciate it!

>
