### ISSUE TITLE
Docker image build fails - perl-db_file (no such package):

### ISSUE THREAD

**Issue by zarafc** [timlegge/docker-foswiki#38]
Hello

For info. The build breaks this PM. It ran ok this morning.
What has changed?
.
.

_Executing busybox-1.32.0-r7.trigger
OK: 6 MiB in 14 packages
OK: 6 MiB in 14 packages
  perl-db_file (no such package):
ERROR: unable to select packages:
    required by: world[perl-db_file]
  perl-db_file-lock (no such package):
    required by: world[perl-db_file-lock]_
.
.

Thanks for any feedback

**Comment by timlegge** [comment]
Hi

https://gitlab.alpinelinux.org/alpine/aports/-/commit/5a48ee640c1340bf3c54aef8f4c29811f82333cc

db_file and db_file-lock have been removed from AlpineLinux packages
due to licensing concerns.

I will need to either build the packages specifically or install from
cpan.  It is possible that the underlying library is gone as well.  It
will be a few days (PR welcome)

TIm

**Comment by zarafc** [comment]
Hi Tim
Thanks for the quick feedback

I'd be happy to help but Ive not built these before

**Comment by timlegge** [comment]
If you don't actually need db_file  db_file-lock simply remove them from
the Dockerfile.

It is used by LdapContrib for sure but i am not sure what else

Tim

**Comment by zarafc** [comment]
Unfortunately we use Ldap and these modules are therefore needed.
I will also checkout how to build these packages,
Regards

**Comment by timlegge** [comment]
Hi

This is from memory, modify the Dockerfile

Remove perl-db_file and perl-db_file-lock and add a new section :

RUN perl -MCPAN -e 'install DB_File DB_File-Lock'

after all the packages are selected and before Foswiki is installed

Tim

**Comment by timlegge** [comment]
fixed in master - will be in the next release
